In [ ]:
#Q2  Write a program to input a string and check whether it is palindrome or not

a=input("enter a string")
if (a==a[::-1]):
    print("palindrome")
else:
    print("not palindrome")


enter a string gfgh


not palindrome


In [20]:
#Q3 Write a program to input a string and count the number of words in it


def cw(s):
    words = s.split()
    return len(words)
a = input("Enter a string: ")
word_count = cw(a)
print("Number of words in the string:", word_count)


Enter a string:   program to input a string and remove the duplicate words


Number of words in the string: 10


In [21]:
#Q4 Write a program to input a string and remove the duplicate words

s=input("enter a string")
s1=''
words=s.split()
w=set(words)
s1=''.join(w)
print(s1)

enter a string hii hii hiii saurav saurav


hiiihiisaurav


In [1]:
#Q5 Write a Python program to find the common elements between two lists.


l1=[1,2,3,44,44,5,6]
l2=[9,8,6,4,33,44,6]
c_e=[element for element in l1 if element in l2]
print("common element",c_e)



common element [44, 44, 6]


In [5]:
#Q6  Write a Python program to interchange first and last elements in a list


def interchange(list):
    if len(list)>2:
        list[0],list[-1]=list[-1],list[0]
l=[1,2,3,45,6,8]
interchange(l)
print(l)


[8, 2, 3, 45, 6, 1]


In [2]:
#Q7(a) Write a Python Program to create an 1D array with 5 elements

import numpy as np
a= np.array([1, 2, 3, 4, 5])
print(a)


[1 2 3 4 5]


In [8]:
#Q7(b)  Write a Python Program to create an 2D array with dimension 3,3

import numpy as np
a = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])
print("2D Array with dimensions 3x3:")
print(a)



2D Array with dimensions 3x3:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
#Q8(a) Write a Python Program to add two arrays each of dimension 3,3

import numpy as np
a1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
a2 = np.array([[9, 8, 7],
                   [6, 5, 4],
                   [3, 2, 1]])
sum_array = a1 + a2
print("First array:")
print(a1)
print("\nSecond array:")
print(a2)
print("\nSum of the two arrays:")
print(sum_array)


First array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Second array:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Sum of the two arrays:
[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [1]:
#Q8(b)Write a Python Program to add one vector(1d array with 3 elements) with an array of dimension 3,3

import numpy as np
a1=np.array([1,2,3])
a2=np.array([[9, 8, 7],
             [6, 5, 4],
             [3, 2, 1]])
res=np.add(a1,a2)
print(res)

[[10 10 10]
 [ 7  7  7]
 [ 4  4  4]]


In [5]:
#Q9 Write a Python Program to multiply 2 arrays each of dimension 4,4


import numpy as np
a1=np.array([[1,2,3,4],
            [4,5,6,7],
            [8,9,10,11],
            [12,13,14,15]])
a2=np.array([[1,2,3,4],
            [4,5,6,7],
            [8,9,10,11],
            [12,13,14,15]])
result=np.multiply(a1,a2)
print("Result of multiply the two array")
print(result)

Result of multiply the two array
[[  1   4   9  16]
 [ 16  25  36  49]
 [ 64  81 100 121]
 [144 169 196 225]]


In [11]:
#Q10 Write a Python Program to multiply a vector(5 elements) with an array(dimension 5,2)
#      using numpy.dot(arra,arrb) and find the dimension of the resultant matrix


import numpy as np
vector=np.array([1,2,3,4,5])
array=np.array([[1,2],
                [3,4],
                [5,6],
                [7,8],
                [9,10]])
result=np.dot(vector,array)

print("Resultant matrix")
print(result)




Resultant matrix
[ 95 110]
