In [1]:
#Python library is a collection of function and methods that allow you to perform many actions without writting your code.
#numPy stands for numerical python and is the core libarary for numeric and scientific computating


In [2]:
import numpy as np

In [3]:
#single dimansonal array

n1=np.array([1,2,3])
n1

array([1, 2, 3])

In [9]:
l1=[1,2,3,4,5,]

In [10]:
n1=np.array(l1)

array([1, 2, 3, 4, 5])

In [13]:
type(n1)

numpy.ndarray

In [8]:
#multidimansional array

n2=np.array([[1,2,3],[4,5,6],[7,8,9]])
n2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
import numpy as np
n3=np.zeros((5,5))
n3

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
import numpy as np
n1=np.zeros((3,5))
n1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [2]:
import numpy as np
n1=np.full((2,2),63)
n1

array([[63, 63],
       [63, 63]])

In [4]:
n1=np.arange(10,20)
n1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [5]:
n1=np.arange(10,40,5)
n1

array([10, 15, 20, 25, 30, 35])

In [6]:
n1=np.arange(1,101)
n1

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [9]:
n1=np.random.randint(1,101,4)
n1

array([82, 34, 78, 42])

In [10]:
n1=np.random.randint(200,500,10)
n1

array([215, 405, 274, 260, 273, 232, 218, 348, 281, 405])

In [12]:
n1.shape

(10,)

In [13]:
n1=np.arange(1,100,4)
n1

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61, 65,
       69, 73, 77, 81, 85, 89, 93, 97])

In [14]:
n1.shape

(25,)

In [17]:
n1=np.array([1,2,3])
n2=np.array([3,56,6])
np.vstack((n1,n2))

array([[ 1,  2,  3],
       [ 3, 56,  6]])

In [18]:
n1=np.array([1,2,3])
n2=np.array([3,56,6])
np.hstack((n1,n2))

array([ 1,  2,  3,  3, 56,  6])

In [20]:
n1=np.array([1,2,3])
n2=np.array([3,56,6])
np.column_stack((n1,n2))

array([[ 1,  3],
       [ 2, 56],
       [ 3,  6]])

In [22]:
n1=np.array([1,2,3])
n2=np.array([3,56,6])
np.intersect1d(n1,n2)

array([3])

In [24]:
n1=np.array([1,2,3])
n2=np.array([3,56,6])
np.setdiff1d(n1,n2)    #only n1 will print and common part in n2 will removed

array([1, 2])

In [25]:
n1=np.array([1,2,3])
n2=np.array([3,56,6])
np.setdiff1d(n2,n1)   #only n2 wil print and common part in n1 will removed

array([ 6, 56])

In [26]:
n1=np.array([1,2,3])
n2=np.array([3,56,6])
np.sum(n1+n2)                        #here adding all elements

71

In [30]:
n1=np.array([1,2,3])

n1=n1+1
n1

array([2, 3, 4])

In [33]:
n1=np.array([1,2,3])
n1=n1*3
n1

array([3, 6, 9])

In [35]:
n1=np.array([1,2,3])
n1=n1-2
n1

array([-1,  0,  1])

In [36]:
n1=np.array([1,2,3])
n1=n1/4
n1

array([0.25, 0.5 , 0.75])

In [39]:
n1=np.array([1,2,3,232,23,23,23,2321,12,4,4,5,4,54,3])
np.mean(n1)


180.93333333333334

In [40]:
n1=np.array([1,2,3,232,23,23,23,2321,12,4,4,5,4,54,3])
np.median(n1)


5.0

In [41]:
n1=np.array([1,2,3,232,23,23,23,2321,12,4,4,5,4,54,3])
np.average(n1)


180.93333333333334

In [42]:
n1=np.array([1,2,3,232,23,23,23,2321,12,4,4,5,4,54,3])
np.std(n1)


574.7205079186075